# This file is a template, and might need editing before it works on your project.
# Official docker image.
#


image: "docker:latest"
services:
  - name: "docker:dind"
    entrypoint: ["dockerd-entrypoint.sh"]
    command: ["--insecure-registry=registry.tools.shinet.com.cn:32000"]

variables:
  DOCKER_HOST: "tcp://localhost:2375"
  DOCKER_DRIVER: overlay2
  DOCKER_REGISTRY: "registry.tools.shinet.com.cn:32000"

stages:
  - build
  - deploy

build-beta:
  stage: build
  script:
    - docker info
    - docker login -u dockerClient -p MmE5ZjAzMDk0ODI3 $DOCKER_REGISTRY
    - docker build . -t $DOCKER_REGISTRY/repos/conf-cas:beta
    - docker push $DOCKER_REGISTRY/repos/conf-cas:beta
  only:
    - develop

build-prod:
  stage: build
  script:
    - docker info
    - docker login -u dockerClient -p MmE5ZjAzMDk0ODI3 $DOCKER_REGISTRY
    - docker build . -t $DOCKER_REGISTRY/repos/conf-cas:prod
    - docker push $DOCKER_REGISTRY/repos/conf-cas:prod
  only:
    - tags
  when: manual
  allow_failure: false

deploy-beta:
  stage: deploy
  image: "dtzar/helm-kubectl:2.9.1"
  script:
    - KUBECONFIG=./deploy/config helm version
    - KUBECONFIG=./deploy/config helm upgrade
      --install
      --recreate-pods
      --namespace beta-conf-cas
      --set "cas=172.24.4.101:39200"
      --set "confServer.host=conf-server-service.beta-conf-server.svc.cluster.local"
      --set "confServer.port=8080"
      --set "zookeeper.host=zookeeper.zookeeper.svc.cluster.local"
      --set "zookeeper.port=2181"
      --set "zookeeper.root=/beta-cas"
      --set "image.tag=beta"
      beta-conf-cas
      ./deploy/conf-cas
  only:
    - develop

deploy-prod:
  stage: deploy
  image: "dtzar/helm-kubectl:2.9.1"
  script:
    - KUBECONFIG=./deploy/config helm version
    - KUBECONFIG=./deploy/config helm upgrade
      --install
      --recreate-pods
      --namespace prod-conf-cas
      --set "cas=172.24.4.101:39200"
      --set "confServer.host=conf-server-service.prod-conf-server.svc.cluster.local"
      --set "confServer.port=8080"
      --set "zookeeper.host=zookeeper.zookeeper.svc.cluster.local"
      --set "zookeeper.port=2181"
      --set "zookeeper.root=/prod-cas"
      --set "image.tag=prod"
      prod-conf-cas
      ./deploy/conf-cas
  only:
    - tags
