/* eslint-disable import/prefer-default-export */
import mongoose from 'mongoose';

const { Schema } = mongoose;

const schema = new Schema(
  {
    bridgeId: {
      type: String,
      required: true,
      index: true,
    },
    confId: {
      type: String,
      required: true,
      index: true,
    },
    name: {
      type: String,
      index: true,
    },
    key: {
      type: String,
      index: true,
      required: true,
      unique: true,
    },
    groupKey: {
      type: String,
    },
    mainConfID: {
      type: String,
      index: true,
    },
    subConfNumber: {
      type: Number,
    },
    partition: {
      type: Number,
    },

    confAttr: {
      1: {
        confName: String,
        billingCode: String,
        confirmCode: String,
        specInstr: String,
        startTime: String,
        estEndTime: String,
        confType: Number,
        ConfInfo: Number,
        maxParties: Number,
        maxHosts: Number,
        pNREnabled: Number,
        bOHDEnabled: String,
        autoBreakdownEnabled: Number,
        entryExitConfig: String,
        reqFeatures: String,
        dNIS1: String,
        dNIS2: String,
        userFlag1: String,
        userFlag2: String,
        userField1: String,
        userField2: String,
        highProfile: String,
        skipRecordStatusPrompts: String,
        multipleDialoutAttempts: Number,
        remainActive: String,
        totalParticipantSittingCount: Number,
        sumTotalParticipantSittingCount: Number,
        playQAPodiumEnterMessage: Number,
        playQAPodiumExitMessage: Number,
        configurableFields: String,
        playConferenceAlertResetMsg: String,
        playConferenceAlertDisconnectMsg: String,
        userFlag3: String,
        blockSignalRequest: String,
        allowDuplicatePIN: String,
        minimumDialoutDigits: Number,
        maximumDialoutDigits: Number,
        musicSource: Number,
        validPinRequired: Number,
        conferenceHoldWithMusic: String,
        lectureMode: String,
      },
      2: {
        state: Number,
        secure: String,
        iVRFeatureState: Number,
        activeSessionType: Number,
        sessionOwnerID: String,
        sessionState: Number,
        unAttStarted: String,
        recordEnabled: Number,
        recordState: Number,
        leaderRecGreet: Number,
        quickStart: String,
        pCodeValidCt: String,
        firstCallerMsg: Number,
        nextConfQStart: String,
        singleDTMF: String,
        erasureLock: String,
        erasureText: String,
        vettingLevel: String,
        vettingMode: String,
        vettingMsgs: String,
        languageSetting: Number,
        ptyCntIn: String,
        ptyCntOut: String,
        allowConfLevelPasscode: String,
        confLevelPasscode: String,
        allowProjectCode: Number,
        projectCode: String,
        allowSubConf: String,
        activateSubConf: String,
        confUserDef1: String,
        confUserDef2: String,
        internalRecording: String,
        recordingCode: String,
        callFlow: Number,
        operHelpReq: String,
        accountNumber: String,
        hostAudioMode: String,
        guestAudioMode: String,
        vPNPrefix: String,
        mainConfID: String,
        subConfNumber: String,
        allowHostMuteOverride: String,
        allowGuestMuteOverride: String,
        duration: Number,
        vPNPrefixRequired: Number,
        vPNDelimiter: String,
        forcePromptCASDialouts: Number,
        allowIncreasePartyLimit: String,
        passcodeDTMFPattern: Number,
        preferredCodec: Number,
        callingNumber: String,
        cASMultiSummitDialoutRules: String,
        lRGConfParticipants: Number,
        lRGCustomMsgPrimary: Number,
        lRGCustomMsgSecondary: Number,
      },
      3: {
        userLabel1: String,
        userLabel2: String,
        userLabel3: String,
        userLabel4: String,
      },
      4: {
        customerReference: String,
        serviceCode1: String,
        serviceCode2: String,
        serviceCode3: String,
        serviceCode4: String,
        serviceCode5: String,
        muteState: String,
      },
      5: {
        hybridSDKToken: String,
        adhocInstall: String,
        hybridClientURL: String,
        hybridConnectData: String,
        appDetection: String,
        cSPBranding: String,
        cSPHelpTip: String,
        clientHashList: String,
      },
    },

    deleted: {
      type: Boolean,
      index: true,
    },
  },
  {
    timestamps: true,
  },
);

schema.index({ bridgeId: 1, confId: 1 }, { unique: true });

export const Conference = mongoose.model('Conference', schema);
